spring:
  application:
    name: account-service
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:h2:mem:testdb
#    url: ${DB_URL}
    driverClassName: org.h2.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ninetenbankmail@gmail.com
    password: rbfuyhtvgijarkcv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

